version: "2"
services:
  rest-api-back:
    container_name: rest-api-back
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/whosnext_db
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9191:9191"
    networks:
      - whosnext-network
  db:
    container_name: db
    build:
      context: ./database
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - whosnext-network
networks:
  whosnext-network:
    driver: bridge
